name: Auto Approve PR

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  approve:
    if: contains(github.event.comment.body, '/approve') && github.event.comment.user.login == 'q4erty'
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}